/* eslint-disable camelcase */
const film2 = {
  characters: [
    'https://swapi.dev/api/people/1/',
    'https://swapi.dev/api/people/2/',
    'https://swapi.dev/api/people/3/',
    'https://swapi.dev/api/people/4/',
    'https://swapi.dev/api/people/5/',
    'https://swapi.dev/api/people/10/',
    'https://swapi.dev/api/people/13/',
    'https://swapi.dev/api/people/14/',
    'https://swapi.dev/api/people/18/',
    'https://swapi.dev/api/people/20/',
    'https://swapi.dev/api/people/21/',
    'https://swapi.dev/api/people/22/',
    'https://swapi.dev/api/people/23/',
    'https://swapi.dev/api/people/24/',
    'https://swapi.dev/api/people/25/',
    'https://swapi.dev/api/people/26/',
  ],
  created: '2014-12-12T11:26:24.656000Z',
  director: 'Irvin Kershner',
  edited: '2014-12-15T13:07:53.386000Z',
  episode_id: 5,
  opening_crawl:
    'It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....',
  planets: [
    'https://swapi.dev/api/planets/4/',
    'https://swapi.dev/api/planets/5/',
    'https://swapi.dev/api/planets/6/',
    'https://swapi.dev/api/planets/27/',
  ],
  producer: 'Gary Kurtz, Rick McCallum',
  release_date: '1980-05-17',
  species: [
    'https://swapi.dev/api/species/1/',
    'https://swapi.dev/api/species/2/',
    'https://swapi.dev/api/species/3/',
    'https://swapi.dev/api/species/6/',
    'https://swapi.dev/api/species/7/',
  ],
  starships: [
    'https://swapi.dev/api/starships/3/',
    'https://swapi.dev/api/starships/10/',
    'https://swapi.dev/api/starships/11/',
    'https://swapi.dev/api/starships/12/',
    'https://swapi.dev/api/starships/15/',
    'https://swapi.dev/api/starships/17/',
    'https://swapi.dev/api/starships/21/',
    'https://swapi.dev/api/starships/22/',
    'https://swapi.dev/api/starships/23/',
  ],
  title: 'The Empire Strikes Back',
  url: 'https://swapi.dev/api/films/2/',
  vehicles: [
    'https://swapi.dev/api/vehicles/8/',
    'https://swapi.dev/api/vehicles/14/',
    'https://swapi.dev/api/vehicles/16/',
    'https://swapi.dev/api/vehicles/18/',
    'https://swapi.dev/api/vehicles/19/',
    'https://swapi.dev/api/vehicles/20/',
  ],
} as const

export default film2
